blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://spectrum.chat/covid19-scenarios/general/questions-discussions~8d49f461-a890-4beb-84f7-2d6ed0ae503a
    about: Ask questions and discuss with other community members
