
data-for-app:
	python3 generate_data.py \
		--output-scenarios ../src/assets/data/scenarios/scenarios.json \
#		--output-cases ../src/assets/data/case_counts.json  \
#		--output-population ../src/assets/data/country_age_distribution.json \
